In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread("lena.jpg")
cv2.imshow("lena",img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [4]:
#Gaussian Kernel Effect
g_img = cv2.GaussianBlur(img.copy(),(7,7),5)
cv2.imshow("gaussian blur lena",g_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [5]:
#kenel = (17,17),更模糊
g_img2 = cv2.GaussianBlur(img.copy(),(17,17),5)
cv2.imshow("gaussian blur lena",g_img2)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [6]:
#方差小，图像锐化，中心点作用大
g_img3 = cv2.GaussianBlur(img.copy(),(7,7),1)
cv2.imshow("Gaussian blur lena",g_img3)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [7]:
# Gaussian kernel
kernel = cv2.getGaussianKernel(7,5)
print(kernel)

[[0.12895603]
 [0.14251846]
 [0.15133131]
 [0.1543884 ]
 [0.15133131]
 [0.14251846]
 [0.12895603]]


In [8]:
#分步高斯效果
g1_img = cv2.GaussianBlur(img.copy(),(7,7),5)
g2_img = cv2.sepFilter2D(img.copy(),-1,kernel,kernel)
cv2.imshow('g1_blur_lena',g1_img)
cv2.imshow('g2_blur_lena',g2_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [9]:
#2nd derivative : laplacian (双边缘效果)
kernel_lap = np.array([[0,1,0],[1,-4,1],[0,1,0]],np.float32)
lap_img = cv2.filter2D(img.copy(),-1,kernel=kernel_lap)
cv2.imshow("lap_lena",lap_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [10]:
#图像锐化 = edge+ori
kernel_sharpen = np.array([[0,1,0],[1,-3,1],[0,1,0]],np.float32)
lap_img2 = cv2.filter2D(img.copy(),-1,kernel=kernel_sharpen)
cv2.imshow("sharp_lena",lap_img2)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [11]:
#上面的是有问题的，会产生模糊，周围有4个1，中间是-3，虽有边缘效果，但是周围的1会使原kernel有
#滤波效果，使图像变的模糊
#解决：取kernel_lap的相反数，再加上原图像，这样会突出中心像素，效果类似于小方差，既有边缘效果，又可使图像清晰
kernel_sharp = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)
lap_img3 = cv2.filter2D(img.copy(),-1,kernel=kernel_sharp)
cv2.imshow('sharp_lena',lap_img3)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [12]:
#不仅考虑x，y方向上的梯度，同时考虑对角线方向的梯度
kernel_sharp = np.array([[1,1,1],[1,-7,1],[1,1,1]],np.float32)
lap_img4 = cv2.filter2D(img.copy(),-1,kernel=kernel_sharp)
cv2.imshow('sharp_lena',lap_img4)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [13]:
kernel_sharp = np.array([[-1,-1,-1],[-1,9,-1],[-1,-1,-1]],np.float32)
lap_img5 = cv2.filter2D(img.copy(),-1,kernel=kernel_sharp)
cv2.imshow('sharp_lena5',lap_img5)
cv2.imshow('sharp_lena4',lap_img4)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [14]:
#####edge#####

#x
edgex = np.array([[-1,-2,-1],[0,0,0],[1,2,1]],np.float32)
sharp_img = cv2.filter2D(img.copy(),-1,kernel=edgex)
cv2.imshow('edgex_lena',sharp_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [15]:
#y
edgey = np.array([[-1,0,1],[-2,0,2],[-1,0,1]],np.float32)
sharpy_img = cv2.filter2D(img.copy(),-1,kernel=edgey)
cv2.imshow('edgex_lena',sharp_img)
cv2.imshow('edgey_lena',sharpy_img)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [16]:
#角点
rabbit = cv2.imread("rabbit.png")
rabbit_gray = np.float32(cv2.cvtColor(rabbit,cv2.COLOR_BGR2GRAY))
print(rabbit_gray)

[[124. 125. 126. ... 245. 249. 252.]
 [126. 126. 125. ... 217. 230. 242.]
 [125. 126. 126. ... 184. 208. 231.]
 ...
 [246. 227. 200. ... 148. 184. 218.]
 [248. 236. 218. ... 183. 206. 230.]
 [251. 245. 236. ... 217. 230. 242.]]


In [17]:
#float32是显示不出图像的
cv2.imshow("rabbit_gray",rabbit_gray)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [18]:
#看不清是什么：1、float类型，2img_harris是每个pixel对于harris函数的响应值，没有必要去看是什么
img_harris = cv2.cornerHarris(rabbit_gray,2,3,0.05)
cv2.imshow("img_harris",img_harris)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [19]:
print(img_harris)

[[ 1.73339844e-02  1.73339844e-02  8.08105469e-02 ...  4.25243800e+06
   2.40748750e+04  4.29571367e+04]
 [ 1.73339844e-02  1.73339844e-02  8.08105469e-02 ...  4.25243800e+06
   2.40748750e+04  4.29571367e+04]
 [-8.25195294e-03 -8.25195294e-03  5.44921868e-02 ...  1.03473625e+06
  -5.47643062e+05  1.83426875e+05]
 ...
 [ 1.83774531e+05  1.83774531e+05 -7.41143750e+04 ...  1.28037000e+05
  -1.52963675e+06  4.96862812e+05]
 [ 5.76970312e+03  5.76970312e+03 -3.70193844e+05 ... -8.71213750e+05
  -9.49700375e+05  5.26790562e+05]
 [ 1.19033115e+04  1.19033115e+04  6.48545469e+04 ...  5.06646812e+05
   5.43707938e+05  2.94956281e+05]]


In [20]:
img_ha = cv2.dilate(img_harris,None)
cv2.imshow("img_ha",img_ha)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [22]:
thres = 0.05 * np.max(img_harris)
rabbit[img_harris>thres] = [0,255,0]
cv2.imshow("rabbit_harris",rabbit)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [23]:
#####sift######
#create sift class
sift = cv2.xfeatures2d.SIFT_create()
# detect sift 
kp = sift.detect(img,None)
# compute sift descriptor
kp,des = sift.compute(img,kp)
print(des.shape)
img_sift = cv2.drawKeypoints(img,kp,outImage=np.array([]),flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv2.imshow('lena_sift',img_sift)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

(1098, 128)
